apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: bitnami/wordpress
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: wordpress-data
          mountPath: /bitnami/wordpress
        env:
        - name: WORDPRESS_DATABASE_HOST
          value: mysql
        - name: WORDPRESS_DATABASE_PORT_NUMBER
          value: "3306"
        - name: WORDPRESS_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_DATABASE
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_USER
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_PASSWORD
        - name: WORDPRESS_USERNAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: WORDPRESS_USERNAME
        - name: WORDPRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: WORDPRESS_PASSWORD
        - name: WORDPRESS_EMAIL
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: WORDPRESS_EMAIL
      volumes:
      - name: wordpress-data
        persistentVolumeClaim:
          claimName: wordpress-storage
